---
- name: Include normalize_datasets
  ansible.builtin.include_tasks: normalize_datasets.yml
  when: sanoid_datasets | type_debug == "dict"

- name: Include normalize_templates
  ansible.builtin.include_tasks: normalize_templates.yml
  when: sanoid_templates | type_debug == "dict"

- name: Install Sanoid package
  ansible.builtin.package:
    name: "{{ sanoid_package }}"
    state: present

- name: Create Sanoid configuration directory
  ansible.builtin.file:
    name: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Copy Sanoid template
  ansible.builtin.template:
    src: "{{ item | basename }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "/etc/sanoid/sanoid.conf"
