---
- name: Convert templates to list
  set_fact:
    __sanoid_templates_list: "{{ sanoid_templates | dict2items(key_name='name', value_name='options') }}"

- name: Flatten templates
  set_fact:
    __sanoid_templates: "{{ __sanoid_templates | d([]) + [{'name': item.name} | combine(item.options)] }}"
  with_items: "{{ __sanoid_templates_list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Set sanoid_templates to the normalized value
  set_fact:
    sanoid_templates: "{{ __sanoid_templates }}"
