---
- name: Verify
  hosts: all

  tasks:
    - name: Check that Sanoid works and understands the configuration
      ansible.builtin.command: sanoid
      register: run_sanoid
      changed_when: false
      failed_when: run_sanoid.rc > 0
